---
title: "Adam Fire AM Week 7 Assignment"
output: html_notebook
---

# 5.3: 10
```{r}
library("phaseR")
```

```{r}
hamsys <- function(t,y,parameters){
  x <- y[1]
  y <- y[2]
  
  dy <- numeric(2)
  dy[1]= sin(x)*cos(y)
  dy[2] = (2*x)-(cos(x)*sin(y))
  
  return(list(dy))
}
```

```{r}
x <- y<- seq(-4, 4, .1)
hamfunc <- function(x,y){ 
  z <- -((x)^2)+sin(x)*sin(y)
  return(z)
}
```


```{r}
contour(x,y,outer(x,y,hamfunc), levels = seq(-4, 1, .5))
hamsys.field <- flowField(hamsys, xlim = c(-4, 4), ylim = c(-4,4), add = TRUE, col = c("lightblue"))
y0 = matrix(c(-.1, -2, 2.1, -4, -2, 4, .2, -3), ncol = 2, byrow = TRUE)
hamsys.traj <- trajectory(hamsys, y0 = y0, tlim = c(0, 10), col = rep("orange", nrow(y0)))
```
# 5.4: 2
```{r}
lysys <- function(t,y,parameters){
  x <- y[1]
  y <- y[2]
  
  dy <- numeric(2)
  dy[1]= y
  dy[2] = -x - (y/4) + (x^2)
  
  return(list(dy))
}
```

```{r}
x <- y<- seq(-5, 5, .1)
lyfunc <- function(x,y){ 
  z <- (((y)^2)/2) + (((x)^2)/2) - (((x)^3)/3)
  return(z)
}
```


```{r}
contour(x,y,outer(x,y,lyfunc), levels = seq(-4, 1, .6))
lysys.field <- flowField(lysys, xlim = c(-5, 5), ylim = c(-5,5), add = TRUE, col = c("lightblue"))
```